### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [enguerrand/child-monitor#5]
# Possible Memory Leak
An [anonymous inner class](https://stackoverflow.com/questions/17778077/would-anonymous-handler-or-runnable-create-a-memory-leak) will hold a reference to the this pointer of the outer class and will not be released until the thread ends.
It will hold the Activity and prevent its timely release. Please check the links below.

# Occurrences
https://github.com/enguerrand/child-monitor/blob/master/app/src/main/java/de/rochefort/childmonitor/ListenActivity.java#L139
https://github.com/enguerrand/child-monitor/blob/master/app/src/main/java/de/rochefort/childmonitor/MonitorActivity.java#L112

# Possible Solution
If it is necessary, it can be changed to [static class + weak reference](https://stackoverflow.com/questions/22162642/will-handler-inside-a-method-leak-memory/27825703#27825703) to eliminate the reference to the activity, which may cause memory leaks.
Further discussion is welcome.

**Comment by enguerrand** [comment]
Hi, thanks for this suggestion, and sorry for the slow response, my GitHub notification settings were wrong so I only saw it just now.

Did you actually observe high memory usage because of this?
Are you interested to propose a fix through a PR?

**Comment by enguerrand** [comment]
I looked closer at this and I don't understand your point.

The Thread will be interrupted as soon as the activity ends. Both the Activity and the Thread can then be garbage collected.

I will go ahead and close this. If you think I overlooked anything feel free to reopen but please do provide more detailed explanation/evidence that we actually do have a problem here.
