### ISSUE TITLE
Implement foreground service

### ISSUE THREAD

**Issue by ltguillaume** [enguerrand/child-monitor#6]
Currently, Child Monitor can be closed by Android when there's not enough memory. If a foreground service would be implemented (e.g. https://scribe.rip/what-is-foreground-service-in-android-3487d9719ab6), then the parent phone can still be used while streaming, without the risk of being disconnected.

**Comment by wabadoo-wabadee** [comment]
This is a very good point. In android 14, child monitor loses the ability to play the audio stream after some seconds when in the background.

**Comment by enguerrand** [comment]
Hi, thanks for this suggestion, and sorry for the slow response, my GitHub notification settings were wrong so I only saw it just now.
I completely agree that this would be useful.
I will leave this open and try to find the time to look into it but can't promise any timescale.
Until then pull requests are welcome 😉

**Comment by enguerrand** [comment]
This is solved in v1.2. Same goes for the monitor activity (child device.)
Many thanks to @fwiesel for his work on this issue.

I created a MR for inclusion of v1.2 into fdroid, so I'll go ahead and close this issue.
