### ISSUE TITLE
[Feature Request] Lockscreen app

### ISSUE THREAD

**Issue by Mannshoch** [enguerrand/child-monitor#8]
Please add a PitchBlack Lockscreen app.

- [ ] That shows in an adjustable color if the connection with the Child app is working. 
- [ ] The last measured peaks.
- [ ] A button to switch between peak only audio for sleeping and permanent audio.

The Idea behind that:

1. Usable in the middle of the night in the Parents sleeping room 
2. dark screen with a dark grey or red Information on it. That saves Energy and is good to read in the dark.

**Comment by enguerrand** [comment]
Hi, thanks for this feature suggestion. However, while I agree that this functionality is desirable, I personally don't have a use case for it, so I am not going to implement it.
I am happy to look at Pull Requests through.
